# Generated by Django 6.0.1 on 2026-01-21 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lista_tareas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarea',
            name='estado',
            field=models.IntegerField(choices=[('1', 'Pendiente'), ('2', 'En_progreso'), ('3', 'Completado')], default=1),
        ),
    ]
